name: cpu-tests
on:
  push:
    branches: [ main ]
jobs:
  cpu-test-job:
    runs-on: cpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc:latest
    steps:
      - name: Check for AXLearn test script for CPU
        run: ls /root/setup/cpu.sh && echo found AXLearn tests
      - name: Run tests for CPU platform
        run: (/bin/bash /root/setup/cpu.sh) || (echo Tests failed)