name: cpu-unit-tests
on:
  workflow_dispatch
jobs:
  cpu-unit-tests-job:
    runs-on: cpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-cpu:latest
    steps:
      - name: Check for AXLearn test script for CPU
        run: ls /root/cpu-unit-tests.sh && echo found AXLearn tests
      - name: Run tests for CPU platform
        run: (/bin/bash /root/cpu-unit-tests.sh) || (echo Tests failed)