name: gpu-training-test
on:
  workflow_dispatch
jobs:
  gpu-training-test-job:
    runs-on: gpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-gpu:latest
    steps:
      - name: Check for AXLearn test script for GPU
        run: ls /root/gpu.sh && echo found AXLearn tests
      - name: Run tests for GPU platform
        run: () || (echo Tests failed)