### Will be in the main branch since scheduler only work in main/master branch
name: jax-nightly-scheduler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  trigger-jax-nightly:
    runs-on: ubuntu-latest
    steps:
      - name: Run JAX Nightly Sequence Training Tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run "jax-nightly-training-tests-sequence" --ref jax_nightly_py3.12