name: jax-nightly-training-tests-sequence

on:
  workflow_dispatch:

jobs:
  run-tpu-single-slice-training-test:
    name: Trigger TPU Single Slice Training Test
    uses: ./.github/workflows/tpu-single-slice-training-test.yaml
  
  run-tpu-multi-slices-training-test:
    name: Trigger TPU Multi-slice Training Test
    uses: ./.github/workflows/tpu-multislice-training-test.yaml
    needs: run-tpu-single-slice-training-test
    if: always()
  
  run-gpu-single-host-training-test:
    name: Trigger GPU Single-host Training Test
    uses: ./.github/workflows/gpu-training-test.yaml
    needs: run-tpu-multi-slices-training-test
    if: always()
  
  run-gpu-multi-slices-training-test:
    name: Trigger GPU Multi-hosts Training Test
    uses: ./.github/workflows/gpu-multihost-training-test.yaml
    needs: run-gpu-single-host-training-test
    if: always()


