name: jax-nightly-scheduler

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  run-tpu-single-slice-training-test:
    runs-on: ubuntu-latest
    if: always()
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run JAX Nightly Sequence Training Tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run tpu-single-slice-training-test.yaml --ref jax_nightly_py3.12
  
  run-tpu-multi-slices-training-test:
    runs-on: ubuntu-latest
    needs: run-tpu-single-slice-training-test
    if: always()
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run JAX Nightly Sequence Training Tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run tpu-multislice-training-test.yaml --ref jax_nightly_py3.12
   
  
  run-gpu-single-host-training-test:
    runs-on: ubuntu-latest
    needs: run-tpu-multi-slices-training-test
    if: always()
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run JAX Nightly Sequence Training Tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run gpu-training-test.yaml --ref jax_nightly_py3.12
  
  run-gpu-multi-slices-training-test:
    runs-on: ubuntu-latest
    needs: run-gpu-single-host-training-test
    if: always()
    permissions:
      actions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run JAX Nightly Sequence Training Tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run gpu-multihost-training-test.yaml --ref jax_nightly_py3.12
