name: pw-elastic-replica-resize-training-test
on:
  workflow_dispatch
jobs:
  pw-elastic-replica-resize-training-test-job:
    runs-on: jobset # Runs on CPU because this schedules a JobSet that's later routed to TPU
    container:
      image: us-central2-docker.pkg.dev/tpu-prod-env-one-vm/camilo-tpu/pw-arc-jobset:latest
      env:
        # Required environmental variables for a successful run
        ARC_JOBSET_NAME: arc-pw-elastic-training
        ARC_JOBSET_JSON: /var/arc/arc-pw-elastic.json
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        JOBSET_DOCKER_IMAGE: us-central2-docker.pkg.dev/tpu-prod-env-one-vm/camilo-tpu/pw-arc-python:latest
        JOBSET_HEALTHY_TIMEOUT: 2100
        ACCELERATOR: v6e_4x4_2
        # Optional flags
        STEPS_CHECKPOINT: 20
        MAX_STEPS: 100
        RESTORE_MODE: True
        ENABLED_REPLICA_RESIZE: True # For elastic training feature Replica Resize
        # RESTORE_MODE: True
        CUSTOM_GIT_ORIGIN: https://github.com/Borklet-Labs/axlearn
        CUSTOM_GIT_BRANCH: cienet/elastic_training # Customize with a different branch
        PW_PROXY_IMAGE: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/proxy_server:20260501-jax_0.10.0
        PW_SERVER_IMAGE: us-docker.pkg.dev/cloud-tpu-v2-images/pathways/server:20260501-jax_0.10.0
        POST_SETUP_CMD: pip install importlib_resources && pip install jax==0.10.0 jaxlib==0.10.0 -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ --extra-index-url https://pypi.org/simple || echo setup_failed

    steps:
      - name: Launch the TPU training job
        id: launch_step
        run: |
          START_TIME=$(date +%s)
          echo "START_TIME=$START_TIME" >> $GITHUB_ENV

          GH_RUN_ID=${{ github.run_id }} python3 /var/arc/launch_jobset.py

          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))

          echo "start_time=$START_TIME" >> $GITHUB_OUTPUT
          echo "end_time=$END_TIME" >> $GITHUB_OUTPUT


  interruption-jobset-replica-resize:
    runs-on: jobset
    container:
      image: us-central2-docker.pkg.dev/tpu-prod-env-one-vm/camilo-tpu/pw-arc-jobset:latest
      env:
        # Required environmental variables for a successful run
        JOBSET_HEALTHY_TIMEOUT: 2100
        CUSTOM_GIT_BRANCH: main # Customize with a different branch
        GCS_PREFIX: gs://axlearn-arc-testing/testing
    steps:
      - name: Launch Node deletion
        id: launch_deletion
        env:
          GH_RUN_ID: ${{ github.run_id }}
          ARC_JOBSET_NAME_TARGET: arc-pw-elastic-training
          DELETE_MODE: drain
        run: |
          START_TIME=$(date +%s)
          echo "START_TIME=$START_TIME" >> $GITHUB_ENV
          START_TIME=$START_TIME GH_RUN_ID=${{ github.run_id }} python /var/arc/validation_utils.py
          echo "start_time=$START_TIME" >> $GITHUB_OUTPUT
      - name: Launch the restore Validation
        env:
          GH_RUN_ID: ${{ github.run_id }}
          START_TIME: ${{ steps.launch_deletion.outputs.start_time}}
          ARC_JOBSET_NAME_TARGET: arc-pw-elastic-training
          VALIDATION_METHOD: restore
          MIN_SLICES: 1
        run: |
          START_TIME=$START_TIME GH_RUN_ID=${{ github.run_id }} python /var/arc/validation_utils.py
