name: tpu-single-slice-training-test
on:
  workflow_dispatch
jobs:
  tpu-single-slice-training-test-job:
    runs-on: jobset # Runs on CPU because this schedules a JobSet that's later routed to TPU
    container:
      image:  us-central2-docker.pkg.dev/tpu-prod-env-one-vm/camilo-tpu/pw-arc-jobset-test:latest
      # image: us-central2-docker.pkg.dev/tpu-prod-env-one-vm/quinn-tpu/pw-arc:latest
      env:
        # Required environmental variables for a successful run
        ARC_JOBSET_NAME: arc-tpu-training-v6e
        ARC_JOBSET_JSON: /var/arc/tpu.json
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        JOBSET_DOCKER_IMAGE:  us-central2-docker.pkg.dev/tpu-prod-env-one-vm/camilo-tpu/pw-arc-python-test:latest
        JOBSET_HEALTHY_TIMEOUT: 900
        ACCELERATOR: v6e_4x4_1
        # Optional flags
        # CUSTOM_GIT_ORIGIN: https://github.com/apple/axlearn # Optionally point to another repo
        CUSTOM_GIT_ORIGIN: https://github.com/Borklet-Labs/axlearn
        CUSTOM_GIT_BRANCH: cienet/0_10_dev
        # JOBSET_MAX_RESTARTS: 1 # Allow restarts in the JobSet. Default = 0 (no restarts)
        # SCHEDULE_TIMEOUT: 600 # Seconds to wait for job to be scheduled. Default = 900
        # POST_SETUP_CMD: uv pip install libtpu==0.0.32.2
        # FUJI_PATCH_FILE: /var/arc/fuji-main.patch # Path to a patch for axlearn/experiments/text/gpt/fuji.py
        ENABLE_JAX_DEV: true
        POST_SETUP_CMD: pip install -v -U --pre jax jaxlib requests libtpu -f https://storage.googleapis.com/libtpu-wheels/index.html --extra-index-url https://storage.googleapis.com/jax-releases/jax_nightly_releases.html -i https://us-python.pkg.dev/ml-oss-artifacts-published/jax/simple/ || echo setup_failed
    steps:
      - name: Launch the TPU training job
        id: launch_job
        run: |
          export GITHUB_OUTPUT=$GITHUB_OUTPUT
          GH_RUN_ID=${{ github.run_id }} python3 /var/arc/launch_jobset.py
      - name: Upload the training result to GCS
        if: always()
        env:
          GCS_PREFIX: gs://axlearn-arc-testing/testing
        run: |
          JAX_VER=${{ steps.launch_job.outputs.jax_version }}
          GH_RUN_ID=${{ github.run_id }} JAX_VER="${JAX_VER}" bash /var/arc/upload-result.sh
