name: tpu-unit-tests
on:
  workflow_dispatch
jobs:
  tpu-unit-tests-job:
    runs-on: tpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-tpu:latest
    steps:
      - name: Setup the AXLearn repo
        run: git init /root && cd /root && git remote add origin https://github.com/apple/axlearn
      - name: Fetch the latest AXLearn commit
        run: cd /root && git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 origin && git checkout main
      - name: Install AXLearn and pytest dependiencies with uv
        run: cd /root && uv pip install --prerelease=allow .[core,tpu,gcp] pytest pytest-instafail allure-pytest torch pytest-xdist
      - name: Create output directories
        run: mkdir -p /home/runner/_work/{xml_results,allure_results}
      - name: Run unit tests
        run: /bin/bash /var/arc/tpu-unit-tests.sh && echo "All tests passed successfully"