name: tpu-unit-tests
on:
  workflow_dispatch
jobs:
  tpu-unit-tests-job:
    runs-on: tpu
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-tpu:python3.12
      env:
        GCS_PREFIX: gs://axlearn-arc-testing/testing
        # Optional flags
        # CUSTOM_GIT_ORIGIN: https://github.com/apple/axlearn # Optionally point to another repo
        CUSTOM_GIT_BRANCH: py3.12_ub24.04
        UV_FIND_LINKS: https://storage.googleapis.com/jax-releases/libtpu_releases.html,https://storage.googleapis.com/axlearn-wheels/wheels.html
    steps:
      - name: Fetch the target AXLearn origin and branch
        run: /bin/bash /var/arc/git-setup.sh
      - name: Install AXLearn and pytest dependiencies with uv
        run: cd /root && uv pip install --prerelease=allow .[core,tpu,gcp] pytest pytest-instafail torch pytest-xdist pytest-csv
      - name: Create output directories
        run: mkdir -p /home/runner/_work/xml_results && mkdir -p /home/runner/_work/csv_results
      - name: Run unit tests
        run: /bin/bash /var/arc/tpu-unit-tests.sh && echo "All tests passed successfully"