name: tpu-multihost-training-test
on:
  workflow_dispatch
jobs:
  tpu-multihost-training-test-job:
    runs-on: jobset # Runs on CPU because this schedules a JobSet that's later routed to TPU
    container:
      image: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-training:latest
      env:
        # Required environmental variables for a successful run
        ARC_JOBSET_NAME: axlearn-tpu-training
        ARC_JOBSET_JSON: /var/arc/tpu.json
        GCS_PREFIX: gs://axlearn-arc-testing/a4-sa-test
        TRAINING_DOCKER_IMAGE: us-docker.pkg.dev/supercomputer-testing/axlearn/arc-tpu-py312:latest
        # Optional flags
        # CUSTOM_GIT_ORIGIN: https://github.com/apple/axlearn # Optionally point to another repo
        CUSTOM_GIT_BRANCH: python3.12 # Customize with a different branch
    steps:
      - name: Install the Kubernetes Python SDK
        run: uv pip install kubernetes
      - name: Launch the TPU training job
        run: python3 /var/arc/launch_training.py
